const days = Object.freeze({
    'Nov, friday 17': [
        'ARCADE FIRE',
        'PULP',
        'ALANIS MORISSETTE',
        'ALVVAYS',
        'AUTOMATIC',
        'BELAKO',
        'BOYWITHUKE',
        'BRITTANY HOWARD',
        'BROOKS NIELSEN',
        'CAROLINE ROSE',
        'CLAUD',
        'FEMME LILY FITZ AND THE TANTRUMS',
        'FLEET FOXES',
        'HANNAH STORM',
        'THE HIVES',
        'HOT CHIP',
        'KENNYHOOPLA MILD MINDS',
        'MOTHER MOTHER MUNA',
        'ORION SUN',
        'PHOENIX',
        'ROOSEVELT',
        'SAMPA THE GREAT',
        'SOCCER MOMMY',
        'SOFIE ROYER',
        'THE WALKMEN',
        'TWO DOOR CINEMA CLUB ',
        'UNKNOWN MORTAL ORCHESTRA',
        'YARD ACT',
    ],
    'Nov, Saturday 18': [
        'BLUR',
        'THE BLACK KEYS',
        'THIRTY SECONDS TO MARS',
        'ALICE IVY',
        'ATARASHII GAKKO!',
        'BARNS COURTNEY',
        'BEN HOWARD ',
        'BILLIE MARTEN',
        'BLACK KIDS',
        'DEAN LEWIS',
        'FEVER RAY',
        'FLETCHER',
        'GIANT ROOKS',
        'AWN',
        'JUNGLE',
        'KASABLIUI',
        'KIM PETRAS ',
        'KIMBRA',
        'THE LA1HUMS',
        'LAW',
        'METRONOMY',
        'NATION OF LANGUAGE ',
        'NEIL FRANCES',
        'HIALL HORAN',
        'OLIVIA DEAN',
        'PARCELS',
        'PATRICK WATSON',
        'REBECCA BLACK',
        'TESSA VIOLET',
    ],
    'Nov, Sunday 19': [
        'THE CURE',
        'THE CHEMICAL BROTHERS',
        'PET SHOP BOYS',
        'THE AMAZONS',
        'ARLO PARKS',
        'BERLIN',
        'THE BREEDERS',
        'D4VD ',
        'DEHD',
        'FEIST',
        'GOOSE',
        'GRACE IVES',
        'GRACIE ABRAMS',
        'THE HAPPY FITS',
        'LADYTRON',
        'THE LUMINEERS',
        'HAI PALM',
        'NF',
        "NOEL GALLAGHER'S HIGH FLYING BIRDS",
        'OFF!',
        'SLEATER-KINNEY',
        'SYLVAN ESSO',
        'TENNIS',
        'THE TWILIGHT SAD',
        'ZHU'
    ]
});
